### PR TITLE
Resolved 

### LINKED ISSUE #56: Log details still showing details after clearing the logs
The log details view is still showing a log even after the clear button was clicked to clear all logs.

I expected the details view to have been cleared together with the log view table.

### PR DESCRIPTION
**Pull request by himanshujaidka**

### CODE REVIEW

**Comment by himanshujaidka** [comment]
issue no #56

**Comment by rpl** [comment]
@himanshujaidka here are some comments on this pull request:

- "Resolved" isn't a meaningful name for a pull request, it doesn't really tell anything about what the pull request is about, please try to put some effort in choosing a pull request title that is meaningful (possibly one that follows the same convention suggested for the commit message here in the contributing guide: https://github.com/mozilla/extension-activity-monitor/blob/master/CONTRIBUTING.md#writing-commit-message).
  - In this case, a reasonable pull request title could be: "fix: close log details sidebar along with clearing all logs in the log-view table" or something like that.
  - As also mentioned explicitly [in the "Creating a pull request" section of the contributing guide](https://github.com/mozilla/extension-activity-monitor/blob/master/CONTRIBUTING.md#creating-a-pull-request), a "Fixes #ISSUENUMBER" should be added to the pull request description (not in a comment of the pull request), this way github should link the pull request to the issue (and also close the issue if and when the pull request is merged)

- as I described in https://github.com/mozilla/extension-activity-monitor/issues/56#issuecomment-704432760 the log-view webcomponent is responsible for managing the sidebar internally, and so my suggestion was to apply the single line change in `src/lib/web-component/log-view/log-view-element.js` (and this PR at the moment is actually changing the `src/lib/ext-activitylog.js`, which isn't the source file that my comment was pointing to)

- the CI job is failing, you should always try to run locally the code quality checks (prettier, linting and tests), this is also part of what the contributing guide is meant to be used for: 
  - https://github.com/mozilla/extension-activity-monitor/blob/master/CONTRIBUTING.md#checking-for-linter
  - https://github.com/mozilla/extension-activity-monitor/blob/master/CONTRIBUTING.md#checking-for-prettier
  - https://github.com/mozilla/extension-activity-monitor/blob/master/CONTRIBUTING.md#writing--running-tests

Next steps for you would be:
- read the https://github.com/mozilla/extension-activity-monitor/blob/master/CONTRIBUTING.md file and follow the guidance tips provided
- provide meaningful pull request title and description, double-check that what you write is concise enough but also helpful to the reviewers to understand what the pull request is for, what it is meant to do (what part of the work is done and what is pending more work if necessary)
- update the change in this PR to follow what we were discussing in the issue 
- keep in mind the feedback that you got from the maintainers/reviewers, describe your reasons if you don't follow what is being suggested
- look into testing the change you are working on: how would you test it? have you read the section in the contributing guide related to writing and running the unit tests? have you looked to the existing unit tests? is there anything in there that you don't understand yet? experiment a bit locally to get a better picture of how that works then try to write your test and submit it here for feedback (and eventually make questions, clear and concise, about what you don't get or what doesn't work)

**Review by rpl — CHANGES_REQUESTED** [review]
set pr status accordingly (details described in https://github.com/mozilla/extension-activity-monitor/pull/86#issuecomment-704884177)

**Comment by himanshujaidka** [comment]
ok, @rpl sir, sorry for the carelessness, I was happy at that moment after solving that bug so I took causally, sorry for this inconvenience, I will improve it, sorry once again sir, in future I will take care of all these points but I have a question, that now I have to follow the path that you have suggested or will proceed with it?

**Pull request closed without merging**
