### PR TITLE
fix: close log details sidebar along with clearing all logs in the log-view table and update dependencies

### PR DESCRIPTION
**Pull request by himanshujaidka**
Fixes issue number #56, and this pull request also update jest version and update all dependencies and the code successfully cleared all test cases. Thank you @Rob--W @rpl @wagnerand @atiqueahmedziad for your guidance.

### CODE REVIEW

**Comment by rpl** [comment]
@himanshujaidka Closing a pull request to address a previous round of review comment isn't a good strategy, for both the developer and the reviewer, e.g. because the context of the previous review does get lost ("lost" as in "easily forgotten") in the closed one. There are many resources online that can help you to learn how to create, update and rebase git branches, and how to work efficiently on a pull requests that is being reviewed, and has to be updated. I'd suggest you to read some of those resources and practice a bit that knowledge (in isolation, e.g. in your own github repository and local git clone).

Besides that:
- in a pull request you should only include the changes that are relevant for the goal of the pull request, this PR should have been a single line change to fix the issue (and then a new test case or a new test assertion to cover it), instead:
  - the PR is updating npm dependencies that shouldn't be updated in this PR and reformatting source files completely unrelated to this change (and none of those changes are actually relevant for the goal of this pull request)
- I'm not really sure that I get the `now I have to follow the path that you have suggested or will proceed with it?` part of the comment from https://github.com/mozilla/extension-activity-monitor/pull/86#issuecomment-705001144, but if you ask feedback and you get it... well then you should follow the "path" described by that feedback or explicitly describe the reasons why you are not following it

Now...
- **remove from this PR everything that is unrelated to the actual goal of the change**
- **do not close this PR and then open a new one!!!** improving your workflow is as important (I would say more important) than the change in the PR that you are creating here: learn and practice how to update the existing PR when you get a review ("shortcuts" like "closing this PR and opening a new one" does not scale and are not going to be acceptable)

We (we as "reviewers / maintainers" of this project) do take the time needed to provide you with a good feedback (detailed and actionable), please be sure that you do take the time needed to read, understand and process the feedback you get before asking more from the "reviewers / maintainers".

**Comment by himanshujaidka** [comment]
sorry @rpl, I have made a new pr, after making pr I read your message sorry sir, now what to do, it's really confusing

**Comment by rpl** [comment]
> sorry @rpl, I have made a new pr, after making pr I read your message sorry sir, now what to do, it's really confusing

a good start would be to follow the suggestions from the previous feedback comments (https://github.com/mozilla/extension-activity-monitor/pull/86#issuecomment-705001144 and https://github.com/mozilla/extension-activity-monitor/pull/87#issuecomment-705073631), starting from: *be sure that you do take the time needed to read, understand and process the feedback you get before asking more from the "reviewers / maintainers"*.

Now I'm going to comment one more time in the new one, but please avoid to keep closing and opening new pull request, as I already wrote you in the comments linked above if you are unable to update a pull request that means that your experience with git has to improve and you should practice your workflow in isolation in your own repositories.

**Comment by himanshujaidka** [comment]
now, I am not at that moment to say anything. But one thing I want to say that in the future I will take care of all those points which you taught me till now. and it's my honor that I will learn something new from all this stuff

**Pull request closed without merging**
