### PR TITLE
Trying to clear all log details

### PR DESCRIPTION
**Pull request by himanshujaidka**
I request all the mentors to review my PR, regarding clear all the log details, and pls tell me that I am doing right or wrong?

### CODE REVIEW

**Comment by wagnerand** [comment]
Thank you for this patch. In your first comment (not in the title), can you please add "Fix #56", so the issue is referenced and gets automatically closed when this PR is merged?

Also, there are some test failures that you might want to look into.

**Comment by himanshujaidka** [comment]
It won't fix the #56 yet, I am working on that so I need a review from you that I am on the right path or not?

**Comment by wagnerand** [comment]
I think you want to test your patch locally, and also run the test suite to make sure it works and doesn't cause any regressions.

**Comment by himanshujaidka** [comment]
Okay, I will run it locally

**Pull request closed without merging**
